### PR TITLE
Add application lifecycle ref

### PR DESCRIPTION
**Pull request by will-sargent-eero**

### CODE REVIEW

**Comment by ornicar** [comment]
Thank you for looking into that issue.
Yes, your change solves the symptom. But the root issue remains.

We can indeed cleanup (or better, prevent) state in our scala objects. But we can't do it when it happens in a third party library. Such as Kamon.

See the `kamon` branch of this repo: https://github.com/ornicar/play-cdi-leak/tree/kamon

I also observed the leak when using Caffeine's system scheduler, but I don't have a branch for that one yet.

**Comment by will-sargent-eero** [comment]
@ornicar that's an issue with Kamon, I'm afraid.  It looks like Kamon disavows any kind of cleanup for devmode -- if you look at the guice module it doesn't even unload it in dev mode https://github.com/kamon-io/kamon-play/blob/master/kamon-play/src/main/scala/kamon/instrumentation/play/GuiceModule.scala#L26

Play 2.8.0 removes global state completely so there is no more `Play.current` and this is exactly why -- long running dev cycles in sbt result in multiple applications being loaded but resources are never released from singletons.  Akka also went through the same thing (much earlier) for the same reasons.

If you want to run Play in a "forked" mode then you can use `runProd` at the cost of some ramp up time, but will get better agent capabilities etc.  And if you want to do something larger scale you can use `docker:publishLocal` with https://github.com/wsargent/sbt-with-jdk-13-docker-logging-example

**Comment by lakinwecker** [comment]
We don't want to run it in forked mode. That was my misguided attempt to figure out what is going on. Sorry for the confusion on that front.

**Comment by ornicar** [comment]
Agreed @will-sargent-eero . I did file an issue on the Kamon repo: https://github.com/kamon-io/Kamon/issues/629

We used to run Play 2.4 with sbt 0.13, and never had any classloader leak. I remember coding for hours without ever restarting sbt. Good times. So there has to be a regression somewhere, right?

**Pull request merged**
